### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Pazengaz** [MRepoApp/MRepo#132]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [X] I'm using the latest version of MRepo. / 我正在使用 MRepo 的最新版本。

### Bug description / Bug 描述

Crash app after install module

### Expected behavior / 预期行为

Crash app

### Actual behavior / 实际行为

Crash app

### Steps to reproduce / 复现步骤

Install Zygisk IFW enhance
Reboot phone
Open App
Crash app

### UI / OS

Miu

### Android Version / Android 版本

9

### Additional info / 额外信息

Xiaomi redmi note 6 pro
3/32GB

FATAL EXCEPTION: main
Process: com.sanmer.mrepo, PID: 9067
java.lang.NoSuchMethodError: No virtual method getClipToOutline()Z in class Landroid/view/RenderNode; or its super classes (declaration of 'android.view.RenderNode' appears in /system/framework/framework.jar!classes2.dex)
	at com.sanmer.mrepo.ba2.m(Unknown Source:2)
	at com.sanmer.mrepo.ga2.g(Unknown Source:28)
	at com.sanmer.mrepo.ir1.i1(Unknown Source:203)
	at com.sanmer.mrepo.ir1.h1(Unknown Source:232)
	at androidx.compose.ui.graphics.BlockGraphicsLayerElement.o(Unknown Source:28)
	at com.sanmer.mrepo.br1.h(Unknown Source:18)
	at androidx.compose.ui.node.a.X(Unknown Source:174)
	at com.sanmer.mrepo.vx.n0(Unknown Source:55)
	at com.sanmer.mrepo.gy.a(Unknown Source:281)
	at com.sanmer.mrepo.gy.k0(Unknown Source:43)
	at com.sanmer.mrepo.yy.l(Unknown Source:59)
	at com.sanmer.mrepo.yy.k(Unknown Source:5)
	at com.sanmer.mrepo.d92.a(Unknown Source:102)
	at com.sanmer.mrepo.fy.a(Unknown Source:9)
	at com.sanmer.mrepo.fy.a(Unknown Source:9)
	at com.sanmer.mrepo.yy.e(Unknown Source:10)
	at com.sanmer.mrepo.u31.c(Unknown Source:114)
	at com.sanmer.mrepo.q31.v(Unknown Source:136)
	at com.sanmer.mrepo.th2.t0(Unknown Source:784)
	at com.sanmer.mrepo.ge1.g(Unknown Source:32)
	at com.sanmer.mrepo.r31.g(Unknown Source:8)
	at com.sanmer.mrepo.qm0.b(Unknown Source:639)
	at com.sanmer.mrepo.qm0.o(Unknown Source:70)
	at com.sanmer.mrepo.bi3.O(Unknown Source:64)
	at com.sanmer.mrepo.zt2.a(Unknown Source:66)
	at com.sanmer.mrepo.au2.c(Unknown Source:70)
	at com.sanmer.mrepo.bw1.a(Unknown Source:12)
	at com.sanmer.mrepo.m31.i(Unknown Source:137)
	at com.sanmer.mrepo.m31.z0(Unknown Source:112)
	at com.sanmer.mrepo.ww0.c0(Unknown Source:17)
	at com.sanmer.mrepo.b22.c(Unknown Source:33)
	at com.sanmer.mrepo.l31.o(Unknown Source:14)
	at com.sanmer.mrepo.bi3.O(Unknown Source:64)
	at com.sanmer.mrepo.zt2.a(Unknown Source:66)
	at com.sanmer.mrepo.au2.c(Unknown Source:70)
	at com.sanmer.mrepo.bw1.a(Unknown Source:12)
	at com.sanmer.mrepo.m31.A0(Unknown Source:100)
	at androidx.compose.ui.node.a.L(Unknown Source:29)
	at com.sanmer.mrepo.de1.j(Unknown Source:201)
	at com.sanmer.mrepo.de1.d(Unknown Source:112)
	at androidx.compose.ui.platform.AndroidComposeView.i(Unknown Source:7)
	at com.sanmer.mrepo.m31.B0(Unknown Source:49)
	at com.sanmer.mrepo.m31.d(Unknown Source:105)
	at com.sanmer.mrepo.mb.c(Unknown Source:35)
	at com.sanmer.mrepo.ww0.d(Unknown Source:45)
	at com.sanmer.mrepo.va.d(Unknown Source:107)
	at com.sanmer.mrepo.va.k0(Unknown Source:673)
	at com.sanmer.mrepo.y21.c(Unknown Source:12)
	at com.sanmer.mrepo.a31.d(Unknown Source:10)
	at com.sanmer.mrepo.j31.a(Unknown Source:13)
	at com.sanmer.mrepo.j31.o(Unknown Source:7)
	at com.sanmer.mrepo.bi3.O(Unknown Source:64)
	at com.sanmer.mrepo.zt2.a(Unknown Source:66)
	at com.sanmer.mrepo.au2.c(Unknown Source:70)
	at com.sanmer.mrepo.bw1.a(Unknown Source:12)
	at com.sanmer.mrepo.m31.B0(Unknown Source:104)
	at com.sanmer.mrepo.de1.c(Unknown Source:54)
	at com.sanmer.mrepo.de1.j(Unknown Source:109)
	at com.sanmer.mrepo.de1.d(Unknown Source:112)
	at androidx.compose.ui.platform.AndroidComposeView.i(Unknown Source:7)
	at com.sanmer.mrepo.m31.B0(Unknown Source:49)
	at com.sanmer.mrepo.m31.d(Unknown Source:105)
	at com.sanmer.mrepo.th2.t0(Unknown Source:813)
	at com.sanmer.mrepo.ge1.g(Unknown Source:32)
	at com.sanmer.mrepo.r31.g(Unknown Source:8)
	at com.sanmer.mrepo.qm0.b(Unknown Source:639)
	at com.sanmer.mrepo.qm0.o(Unknown Source:70)
	at com.sanmer.mrepo.bi3.O(Unknown Source:64)
	at com.sanmer.mrepo.zt2.a(Unknown Source:66)
	at com.sanmer.mrepo.au2.c(Unknown Source:70)
	at com.sanmer.mrepo.bw1.a(Unknown Source:12)
	at com.sanmer.mrepo.m31.i(Unknown Source:137)
	at com.sanmer.mrepo.m31.z0(Unknown Source:112)
	at com.sanmer.mrepo.ww0.c0(Unknown Source:17)
	at com.sanmer.mrepo.b22.c(Unknown Source:33)
	at com.sanmer.mrepo.l31.o(Unknown Source:14)
	at com.sanmer.mrepo.bi3.O(Unknown Source:64)
	at com.sanmer.mrepo.zt2.a(Unknown Source:66)
	at com.sanmer.mrepo.au2.c(Unknown Source:70)
	at com.sanmer.mrepo.bw1.a(Unknown Source:12)
	at com.sanmer.mrepo.m31.A0(Unknown Source:100)
	at androidx.compose.ui.node.a.L(Unknown Source:29)
	at com.sanmer.mrepo.de1.j(Unknown Source:201)
	at com.sanmer.mrepo.de1.f(Unknown Source:99)
	at androidx.compose.ui.platform.AndroidComposeView.onLayout(Unknown Source:4)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at com.sanmer.mrepo.t.e(Unknown Source:27)
	at com.sanmer.mrepo.t.onLayout(Unknown Source:6)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:757)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2872)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2399)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1534)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7421)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
	at android.view.Choreographer.doCallbacks(Choreographer.java:888)
	at android.view.Choreographer.doFrame(Choreographer.java:819)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by SanmerDev** [comment]
Links https://issuetracker.google.com/issues/228094555
