### ISSUE TITLE
Settings/Modules crash [BUG] 

### ISSUE THREAD

**Issue by shuvashish76** [MRepoApp/MRepo#163]
### Checklist

- [X] No one has submitted a similar or identical bug report before
- [X] I'm using the latest version of MRepo

### Bug description

App keeps crashing when I click Settings or Modules

### Expected behavior

Open settings & modules page without any crash.

### Actual behavior

App crashed

Logs:

```
FATAL EXCEPTION: main
Process: com.sanmer.mrepo, PID: 17093
java.lang.IllegalArgumentException: unsupported platform: u:r:magisk:s0
	at android.os.Parcel.createException(Parcel.java:1954)
	at android.os.Parcel.readException(Parcel.java:1918)
	at android.os.Parcel.readException(Parcel.java:1868)
	at com.sanmer.mrepo.ls0.c(Unknown Source:20)
	at com.sanmer.mrepo.ku2.c(Unknown Source:4)
	at com.sanmer.mrepo.s32.a(Unknown Source:4)
	at com.sanmer.mrepo.qx.a(Unknown Source:610)
	at com.sanmer.mrepo.qx.j0(Unknown Source:52)
	at com.sanmer.mrepo.cu.a(Unknown Source:50)
	at com.sanmer.mrepo.cu.j0(Unknown Source:8)
	at com.sanmer.mrepo.pa.a(Unknown Source:168)
	at com.sanmer.mrepo.pa.m0(Unknown Source:27)
	at com.sanmer.mrepo.cu.m0(Unknown Source:58)
	at com.sanmer.mrepo.o90.b(Unknown Source:3009)
	at com.sanmer.mrepo.o90.m0(Unknown Source:384)
	at com.sanmer.mrepo.cu.m0(Unknown Source:58)
	at com.sanmer.mrepo.r30.I0(Unknown Source:19)
	at com.sanmer.mrepo.sx.s(Unknown Source:132)
	at com.sanmer.mrepo.sx.k(Unknown Source:13)
	at com.sanmer.mrepo.xx.p(Unknown Source:18)
	at com.sanmer.mrepo.w52.a(Unknown Source:45)
	at com.sanmer.mrepo.ex.a(Unknown Source:9)
	at com.sanmer.mrepo.ex.a(Unknown Source:9)
	at com.sanmer.mrepo.xx.e(Unknown Source:10)
	at com.sanmer.mrepo.d21.c(Unknown Source:114)
	at com.sanmer.mrepo.z11.v(Unknown Source:136)
	at com.sanmer.mrepo.he2.s0(Unknown Source:784)
	at com.sanmer.mrepo.ec1.g(Unknown Source:32)
	at com.sanmer.mrepo.a21.g(Unknown Source:8)
	at com.sanmer.mrepo.jk0.b(Unknown Source:457)
	at com.sanmer.mrepo.jk0.o(Unknown Source:82)
	at com.sanmer.mrepo.me3.I(Unknown Source:64)
	at com.sanmer.mrepo.br2.a(Unknown Source:66)
	at com.sanmer.mrepo.cr2.c(Unknown Source:70)
	at com.sanmer.mrepo.ct1.a(Unknown Source:12)
	at com.sanmer.mrepo.v11.i(Unknown Source:107)
	at com.sanmer.mrepo.v11.y0(Unknown Source:112)
	at com.sanmer.mrepo.xu0.b0(Unknown Source:17)
	at com.sanmer.mrepo.zy1.c(Unknown Source:33)
	at com.sanmer.mrepo.u11.o(Unknown Source:14)
	at com.sanmer.mrepo.me3.I(Unknown Source:64)
	at com.sanmer.mrepo.br2.a(Unknown Source:66)
	at com.sanmer.mrepo.cr2.c(Unknown Source:70)
	at com.sanmer.mrepo.ct1.a(Unknown Source:12)
	at com.sanmer.mrepo.v11.z0(Unknown Source:100)
	at com.sanmer.mrepo.v11.b0(Unknown Source:76)
	at com.sanmer.mrepo.zy1.c(Unknown Source:33)
	at com.sanmer.mrepo.si.b(Unknown Source:44)
	at com.sanmer.mrepo.pi.s0(Unknown Source:24)
	at com.sanmer.mrepo.ec1.g(Unknown Source:32)
	at com.sanmer.mrepo.jk0.b(Unknown Source:457)
	at com.sanmer.mrepo.jk0.o(Unknown Source:82)
	at com.sanmer.mrepo.me3.I(Unknown Source:64)
	at com.sanmer.mrepo.br2.a(Unknown Source:66)
	at com.sanmer.mrepo.cr2.c(Unknown Source:70)
	at com.sanmer.mrepo.ct1.a(Unknown Source:12)
	at com.sanmer.mrepo.v11.i(Unknown Source:107)
	at com.sanmer.mrepo.v11.y0(Unknown Source:112)
	at com.sanmer.mrepo.xu0.b0(Unknown Source:17)
	at com.sanmer.mrepo.zy1.g(Unknown Source:54)
	at com.sanmer.mrepo.yh.c(Unknown Source:28)
	at com.sanmer.mrepo.yh.s0(Unknown Source:817)
	at com.sanmer.mrepo.ec1.g(Unknown Source:32)
	at com.sanmer.mrepo.j11.b0(Unknown Source:37)
	at com.sanmer.mrepo.zy1.c(Unknown Source:33)
	at com.sanmer.mrepo.u11.o(Unknown Source:14)
	at com.sanmer.mrepo.me3.I(Unknown Source:64)
	at com.sanmer.mrepo.br2.a(Unknown Source:66)
	at com.sanmer.mrepo.cr2.c(Unknown Source:70)
	at com.sanmer.mrepo.ct1.a(Unknown Source:12)
	at com.sanmer.mrepo.v11.z0(Unknown Source:100)
	at com.sanmer.mrepo.v11.b0(Unknown Source:76)
	at com.sanmer.mrepo.zy1.b(Unknown Source:37)
	at com.sanmer.mrepo.ab.b(Unknown Source:178)
	at com.sanmer.mrepo.ab.s0(Unknown Source:84)
	at com.sanmer.mrepo.ec1.g(Unknown Source:32)
	at com.sanmer.mrepo.jk0.b(Unknown Source:457)
	at com.sanmer.mrepo.jk0.o(Unknown Source:82)
	at com.sanmer.mrepo.me3.I(Unknown Source:64)
	at com.sanmer.mrepo.br2.a(Unknown Source:66)
	at com.sanmer.mrepo.cr2.c(Unknown Source:70)
	at com.sanmer.mrepo.ct1.a(Unknown Source:12)
	at com.sanmer.mrepo.v11.i(Unknown Source:107)
	at com.sanmer.mrepo.v11.y0(Unknown Source:112)
	at com.sanmer.mrepo.xu0.b0(Unknown Source:17)
	at com.sanmer.mrepo.zy1.g(Unknown Source:54)
	at com.sanmer.mrepo.yh.c(Unknown Source:49)
	at com.sanmer.mrepo.yh.s0(Unknown Source:825)
	at com.sanmer.mrepo.ec1.g(Unknown Source:32)
	at com.sanmer.mrepo.j11.b0(Unknown Source:37)
	at com.sanmer.mrepo.zy1.b(Unknown Source:37)
	at com.sanmer.mrepo.xa.s0(Unknown Source:27)
	at com.sanmer.mrepo.ec1.g(Unknown Source:32)
	at com.sanmer.mrepo.j11.b0(Unknown Source:37)
	at com.sanmer.mrepo.zy1.c(Unknown Source:33)
	at com.sanmer.mrepo.u11.o(Unknown Source:14)
	at com.sanmer.mrepo.me3.I(Unknown Source:64)
	at com.sanmer.mrepo.br2.a(Unknown Source:66)
	at com.sanmer.mrepo.cr2.c(Unknown Source:70)
	at com.sanmer.mrepo.ct1.a(Unknown Source:12)
	at com.sanmer.mrepo.v11.z0(Unknown Source:100)
	at com.sanmer.mrepo.v11.b0(Unknown Source:76)
	at com.sanmer.mrepo.zy1.b(Unknown Source:37)
	at com.sanmer.mrepo.sa.s0(Unknown Source:158)
	at com.sanmer.mrepo.ec1.g(Unknown Source:32)
	at com.sanmer.mrepo.jk0.b(Unknown Source:457)
	at com.sanmer.mrepo.jk0.o(Unknown Source:82)
	at com.sanmer.mrepo.me3.I(Unknown Source:64)
	at com.sanmer.mrepo.br2.a(Unknown Source:66)
	at com.sanmer.mrepo.cr2.c(Unknown Source:70)
	at com.sanmer.mrepo.ct1.a(Unknown Source:12)
	at com.sanmer.mrepo.v11.i(Unknown Source:107)
	at com.sanmer.mrepo.v11.y0(Unknown Source:112)
	at com.sanmer.mrepo.xu0.b0(Unknown Source:17)
	at com.sanmer.mrepo.zy1.c(Unknown Source:33)
	at com.sanmer.mrepo.wa.s0(Unknown Source:320)
	at com.sanmer.mrepo.ec1.g(Unknown Source:32)
	at com.sanmer.mrepo.j11.b0(Unknown Source:37)
	at com.sanmer.mrepo.zy1.g(Unknown Source:54)
	at com.sanmer.mrepo.yh.c(Unknown Source:28)
	at com.sanmer.mrepo.yh.s0(Unknown Source:817)
	at com.sanmer.mrepo.ec1.g(Unknown Source:32)
	at com.sanmer.mrepo.j11.b0(Unknown Source:37)
	at com.sanmer.mrepo.zy1.d(Unknown Source:95)
	at com.sanmer.mrepo.vf.c(Unknown Source:154)
	at com.sanmer.mrepo.vf.s0(Unknown Source:2357)
	at com.sanmer.mrepo.ec1.g(Unknown Source:32)
	at com.sanmer.mrepo.j11.b0(Unknown Source:37)
	at com.sanmer.mrepo.zy1.c(Unknown Source:33)
	at com.sanmer.mrepo.u11.o(Unknown Source:14)
	at com.sanmer.mrepo.me3.I(Unknown Source:64)
	at com.sanmer.mrepo.br2.a(Unknown Source:66)
	at com.sanmer.mrepo.cr2.c(Unknown Source:70)
	at com.sanmer.mrepo.ct1.a(Unknown Source:12)
	at com.sanmer.mrepo.v11.z0(Unknown Source:100)
	at androidx.compose.ui.node.a.N(Unknown Source:29)
	at com.sanmer.mrepo.bc1.j(Unknown Source:201)
	at com.sanmer.mrepo.bc1.f(Unknown Source:100)
	at androidx.compose.ui.platform.AndroidComposeView.p(Unknown Source:33)
	at com.sanmer.mrepo.at1.a(Unknown Source:3)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(Unknown Source:18)
	at android.view.View.draw(View.java:20210)
	at android.view.View.updateDisplayListIfDirty(View.java:19082)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:19042)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:19042)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:19042)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:19042)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3318)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3122)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2481)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1463)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7190)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:696)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

Followed by another crash

```
FATAL EXCEPTION: main
Process: com.sanmer.mrepo, PID: 17417
java.lang.IllegalArgumentException: unsupported platform: u:r:magisk:s0
	at android.os.Parcel.createException(Parcel.java:1954)
	at android.os.Parcel.readException(Parcel.java:1918)
	at android.os.Parcel.readException(Parcel.java:1868)
	at com.sanmer.mrepo.ls0.c(Unknown Source:20)
	at com.sanmer.mrepo.ku2.c(Unknown Source:4)
	at com.sanmer.mrepo.s32.a(Unknown Source:4)
	at com.sanmer.mrepo.qx.a(Unknown Source:610)
	at com.sanmer.mrepo.qx.j0(Unknown Source:52)
	at com.sanmer.mrepo.cu.a(Unknown Source:50)
	at com.sanmer.mrepo.gn.a(Unknown Source:136)
	at com.sanmer.mrepo.gn.m0(Unknown Source:99)
	at com.sanmer.mrepo.sx.N(Unknown Source:358)
	at com.sanmer.mrepo.sx.V(Unknown Source:57)
	at com.sanmer.mrepo.sx.s(Unknown Source:171)
	at com.sanmer.mrepo.sx.L(Unknown Source:31)
	at com.sanmer.mrepo.xx.w(Unknown Source:18)
	at com.sanmer.mrepo.w52.o(Unknown Source:102)
	at com.sanmer.mrepo.t52.s0(Unknown Source:392)
	at com.sanmer.mrepo.h9.doFrame(Unknown Source:6)
	at com.sanmer.mrepo.f9.doFrame(Unknown Source:47)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:693)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
	Suppressed: com.sanmer.mrepo.f60: [com.sanmer.mrepo.nx1@932853, com.sanmer.mrepo.uh1@823a590, ks2{Cancelling}@ff8e89, g9@1339e8e]
```

### Steps to reproduce

1. Open the app
2. Give root access permission (Magisk)
3. Click on Settings or Modules option
App crashes 

### UI / OS

Lenovo Tab4 8 plus (LineageOS)

### Android Version

9

### Additional info

Magisk version: 27.0

**Comment by SanmerDev** [comment]
try this: https://github.com/MRepoApp/MRepo/commit/01202de0cfc0a0a5ac09f69dcf0c2b31adfa58b0

**Comment by shuvashish76** [comment]
Installed the debug build, works as expected thanks.
