### ISSUE TITLE
IndexOutOfBoundsException onClick 'Update' button

### ISSUE THREAD

**Issue by YaminMahdi** [MRepoApp/MRepo#179]
### Checklist

- [x] No one has submitted a similar or identical bug report before
- [X] I'm using the latest version of MRepo

### Bug description

java.lang.IndexOutOfBoundsException: Index 12, size 12
	at com.sanmer.mrepo.cL.b(Unknown Source:26)
	at com.sanmer.mrepo.cL.c(Unknown Source:0)
	at com.sanmer.mrepo.ti0.q0(Unknown Source:4)
	at com.sanmer.mrepo.nD.b(Unknown Source:10)
	at com.sanmer.mrepo.KC.a(Unknown Source:17)
	at com.sanmer.mrepo.tD.a(Unknown Source:20)
	at com.sanmer.mrepo.uD.l(Unknown Source:777)
	at com.sanmer.mrepo.Hn.p(Unknown Source:23)
	at com.sanmer.mrepo.Hn.l(Unknown Source:405)
	at com.sanmer.mrepo.iC.c(Unknown Source:79)
	at com.sanmer.mrepo.xy.d(Unknown Source:37)
	at com.sanmer.mrepo.k60.g(Unknown Source:0)
	at com.sanmer.mrepo.PB.d(Unknown Source:10)
	at com.sanmer.mrepo.O20.g(Unknown Source:43)
	at com.sanmer.mrepo.PB.d(Unknown Source:10)
	at com.sanmer.mrepo.k60.g(Unknown Source:0)
	at com.sanmer.mrepo.PB.d(Unknown Source:10)
	at com.sanmer.mrepo.Uq.g(Unknown Source:96)
	at com.sanmer.mrepo.PB.d(Unknown Source:10)
	at com.sanmer.mrepo.ZQ.g(Unknown Source:114)
	at com.sanmer.mrepo.PB.d(Unknown Source:10)
	at com.sanmer.mrepo.ly.b(Unknown Source:41)
	at com.sanmer.mrepo.ly.c(Unknown Source:41)
	at com.sanmer.mrepo.Og0.K(Unknown Source:59)
	at com.sanmer.mrepo.x80.a(Unknown Source:47)
	at com.sanmer.mrepo.y80.c(Unknown Source:152)
	at com.sanmer.mrepo.QQ.a(Unknown Source:2)
	at com.sanmer.mrepo.aC.A0(Unknown Source:106)
	at com.sanmer.mrepo.wH.c(Unknown Source:54)
	at com.sanmer.mrepo.wH.k(Unknown Source:123)
	at com.sanmer.mrepo.wH.e(Unknown Source:110)
	at com.sanmer.mrepo.wH.e(Unknown Source:122)
	at com.sanmer.mrepo.wH.e(Unknown Source:122)
	at com.sanmer.mrepo.wH.d(Unknown Source:38)
	at com.sanmer.mrepo.t3.k(Unknown Source:2)
	at com.sanmer.mrepo.aC.A0(Unknown Source:54)
	at com.sanmer.mrepo.wH.c(Unknown Source:17)
	at com.sanmer.mrepo.wH.m(Unknown Source:17)
	at com.sanmer.mrepo.wH.j(Unknown Source:58)
	at com.sanmer.mrepo.t3.onMeasure(Unknown Source:82)
	at android.view.View.measure(View.java:24604)
	at com.sanmer.mrepo.w.f(Unknown Source:63)
	at com.sanmer.mrepo.w.onMeasure(Unknown Source:3)
	at android.view.View.measure(View.java:24604)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6885)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:24604)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6885)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:24604)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6885)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:767)
	at android.view.View.measure(View.java:24604)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3088)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1912)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2204)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1800)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7771)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
	at android.view.Choreographer.doCallbacks(Choreographer.java:854)
	at android.view.Choreographer.doFrame(Choreographer.java:789)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7520)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

### Expected behavior

Start updating.

### Actual behavior

Crashed. But worked second time.

### Steps to reproduce

1. Opened the app.
2. Clicked on update button of a module.
3. Clicked install.
4. It downloaded.
5. Went to the flashing page.
6. Crushed.
7. Tried second time, it worked.    

### UI / OS

MIUI

### Android Version

11

### Additional info

Android 10.
POCO X2

**Comment by SanmerDev** [comment]
Maybe fixed, you can try this [MRepo-2.4.5.dev.7d82f2b-739-release](https://github.com/MRepoApp/MRepo/actions/runs/8358247237/artifacts/1342251305).
