### ISSUE TITLE
[BUG] Random crash

### ISSUE THREAD

**Issue by NikunjKhangwal** [MRepoApp/MRepo#187]
### Checklist

- [X] No one has submitted a similar or identical bug report before
- [X] I'm using the latest version of MRepo

### Bug description

The app randomly crashed during installation of a module

### Expected behavior

Install the module

### Actual behavior

Crashed

### UI / OS

MIUI

### Android Version

Android 12

### Additional info

Crash Log:

FATAL EXCEPTION: main
Process: com.sanmer.mrepo, PID: 9403
java.lang.NullPointerException
	at com.sanmer.mrepo.IJ.r(Unknown Source:42)
	at com.sanmer.mrepo.Q8.m(Unknown Source:8)
	at com.sanmer.mrepo.jm.run(Unknown Source:114)
	at com.sanmer.mrepo.i1.run(Unknown Source:30)
	at com.sanmer.mrepo.uc0.run(Unknown Source:2)
	at com.sanmer.mrepo.sj.run(Unknown Source:95)
	Suppressed: com.sanmer.mrepo.Sl: [n90{Cancelling}@8a7cee1, Dispatchers.Main.immediate]

**Comment by SanmerDev** [comment]
Too little info I can't determine what the bug is, maybe you can try the dev version.
